// src/components/BestDeals.vue
<template>
    <div>
        <div class='w-11/12 md:w-1/2 xl:w-1/3 m-auto text-center py-10'>
            <h1 class='text-4xl font-bold'>Descubre las Oportunidades Inmobiliarias Imperdibles</h1>
            <p class='text-xs text-gray-400'>Explora una selección exclusiva de propiedades que te brindarán las mejores
                opciones para encontrar tu nuevo hogar. Nuestro equipo está aquí para guiarte en cada paso del camino y
                hacer que tu experiencia sea excepcional.</p>
        </div>
        <div class="deals w-full grid lg:grid-flow-col grid-row-2 gap-8">
            <div v-for="(house, index) in houses" :key="index" class="deal relative" :class="getClass(index)">
                <img :src="house" alt="" class='rounded-xl w-full h-full object-cover' />
                <div class='w-full absolute bottom-0 p-4 text-white bg-gradient-to-t from-black rounded-b-xl space-y-2'>
                    <h1 class='text-3xl font-bold'>LUGAR</h1>
                    <p class='flex items-center space-x-2 text-sm'><io-location-outline />Kissimmee, Florida, EE. UU.
                    </p>
                </div>
            </div>
        </div>
    </div>
</template>

<script>



</script>

<style scoped>
/* Añade tus estilos aquí */
</style>

// src/components/BestDeals.jsx
import house1 from '../assets/house7.jpg'
import house2 from '../assets/house8.jpg'
import house3 from '../assets/house9.jpg'
import house4 from '../assets/house10.jpg'
import house5 from '../assets/house11.jpg'
import house6 from '../assets/house12.jpg'
import { IoLocationOutline } from 'react-icons/io5'

const BestDeals = () => {
    return (
        <div className=''>
            <div className='w-11/12 md:w-1/2 xl:w-1/3 m-auto text-center py-10'>
                <h1 className='text-4xl font-bold'>Descubre las Oportunidades Inmobiliarias Imperdibles</h1>
                <p className='text-xs  text-gray-400'>Explora una selección exclusiva de propiedades que te brindarán las mejores opciones para encontrar tu nuevo hogar. Nuestro equipo está aquí para guiarte en cada paso del camino y hacer que tu experiencia sea excepcional.</p>
            </div>
            <div className="deals w-full  grid lg:grid-flow-col grid-row-2  gap-8">
                <div className="deal relative col-span-2 row-span-2">
                    <img src={house1} alt="" className='rounded-xl w-full h-full object-cover' />
                    <div className='w-full absolute bottom-0 p-4 text-white bg-gradient-to-t from-black rounded-b-xl space-y-2'>
                        <h1 className='text-3xl font-bold'>LUGAR</h1>
                        <p className='flex items-center space-x-2 text-sm'><IoLocationOutline />Kissimmee, Florida, EE. UU.</p>
                    </div>
                </div>
                <div className="deal relative col-span-1 row-span-2">
                    <img src={house2} alt="" className='rounded-xl w-full h-full object-cover' />
                    <div className='w-full absolute bottom-0 p-4 text-white bg-gradient-to-t from-black rounded-b-xl space-y-2'>
                        <h1 className='text-3xl font-bold'>LUGAR</h1>
                        <p className='flex items-center space-x-2 text-sm'><IoLocationOutline />Kissimmee, Florida, EE. UU.</p>
                    </div>
                </div>
                <div className="deal relative  col-span-1 row-span-1">
                    <img src={house3} alt="" className='rounded-xl w-full h-full object-cover' />
                    <div className='w-full absolute bottom-0 p-4 text-white bg-gradient-to-t from-black rounded-b-xl space-y-2'>
                        <h1 className='text-3xl font-bold'>LUGAR</h1>
                        <p className='flex items-center space-x-2 text-sm'><IoLocationOutline />Kissimmee, Florida, EE. UU.</p>
                    </div>
                </div>
                <div className="deal relative col-span-1 row-span-1">
                    <img src={house4} alt="" className='rounded-xl w-full h-full object-cover' />
                    <div className='w-full absolute bottom-0 p-4 text-white bg-gradient-to-t from-black rounded-b-xl space-y-2'>
                        <h1 className='text-3xl font-bold'>LUGAR</h1>
                        <p className='flex items-center space-x-2 text-sm'><IoLocationOutline />Kissimmee, Florida, EE. UU.</p>
                    </div>
                </div>
                <div className="deal relative col-span-1 row-span-1">
                    <img src={house5} alt="" className='rounded-xl w-full h-full object-cover' />
                    <div className='w-full absolute bottom-0 p-4 text-white bg-gradient-to-t from-black rounded-b-xl space-y-2'>
                        <h1 className='text-3xl font-bold'>LUGAR</h1>
                        <p className='flex items-center space-x-2 text-sm'><IoLocationOutline />Kissimmee, Florida, EE. UU.</p>
                    </div>
                </div>
                <div className="deal relative col-span-1 row-span-1">
                    <img src={house6} alt="" className='rounded-xl' />
                    <div className='w-full absolute bottom-0 p-4 text-white bg-gradient-to-t from-black rounded-b-xl space-y-2'>
                        <h1 className='text-3xl font-bold'>LUGAR</h1>
                        <p className='flex items-center space-x-2 text-sm'><IoLocationOutline />Kissimmee, Florida, EE. UU.</p>
                    </div>
                </div>
            </div>
        </div>
    )
}

export default BestDeals
